name: autofix.ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  format-metadata:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: website/typst-docs-web
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - name: Setup tools
        uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Apply Biome checks
        run: bun biome check --write ../
      - name: Autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
